name: anura_flutter
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

flutter:
  plugin:
    platforms:
      android:
        default_package: anura_flutter_android
      ios:
        default_package: anura_flutter_ios

dependencies:
  anura_flutter_android:
    path: ../anura_flutter_android
  anura_flutter_ios:
    path: ../anura_flutter_ios
  anura_flutter_platform_interface:
    path: ../anura_flutter_platform_interface
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: 2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^9.0.0
