name: anura_flutter
packages:
  - anura_flutter/
  - anura_flutter_android/
  - anura_flutter_ios/
  - anura_flutter_platform_interface/

scripts:
  lint:all:
    run: melos run analyze && melos run format
  analyze:
    run: |
      melos exec -c 5 -- \
      dart analyze . --fatal-infos
  format:
    run: |
      melos exec -c 5 -- \
      dart format .
