allprojects {
    repositories {
        maven {
            url = uri("https://git.deepaffex.ai/api/packages/External/maven")// Use the actual URL of the Anura Maven repo
            credentials {
                username = System.getenv("DFX_GIT_USERNAME")
                password = System.getenv("DFX_GIT_TOKEN")
            }
        }
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
